# Title shown in Application Information tab.
title: Fleet Patching and Provisioning Workshop
# Sub Title shown in Application Information tab.
description: Fleet Patching and Provisioning Workshop
stackDescription: "Deploy an FPP Server and FPP Target ready to execute the FPP workshop"
schemaVersion: 1.1.0
version: "20210409"
locale: "en"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=80556488"
# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: image
#  reference: 82618540
#https://cloudmarketplace.oracle.com/marketplace/listing/82618540


outputGroups:
  - title: Access Information for FPP Server and Target
    outputs:
      - ${fppserver}
      - ${fppclient}

variableGroups:
  - title: Tenancy Configuration
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region

  - title: Main Configuration - Required
    visible: true
    variables:
    - availability_domain_name
    - resUserPublicKey

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: "Compartment where you want to create the FPP target and server"

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    title: "Select an availability domain"
    required: true
    description: "All instances will be provisioned in this availability domain"
    dependsOn:
      compartmentId: ${compartment_ocid}

  resUserPublicKey:
    type: text
    required: true
    title: "SSH Public Key"
    description: "Public SSH key for accessing the nodes over SSH as user opc"

  region:
    type: oci:identity:region:name
    required: true
    title: Region
    description: Region where you want to deploy the resources defined by this stack

  vcn_use_existing:
    type: string
    required: false
    visible: false

  vcn_cidr:
    type: string
    required: false
    visible: false

  subnet_cidr:
    type: string
    required: false
    visible: false

  ociUserOcid:
    type: string
    required: false
    visible: false

  fingerprint:
    type: string
    required: false
    visible: false

  private_key_path:
    type: string
    required: false
    visible: false

  ssh_public_key:
    type: string
    required: false
    visible: false

  ssh_private_key:
    type: string
    required: false
    visible: false

  ociUserPassword:
    type: string
    required: false
    visible: false

  subnet_public_existing:
    type: string
    required: false
    visible: false

outputs:
  fppserver:
    type: string
    title: FPP Server
    displayText: FPP Server Name and public IP
    visible: true

  fppclient:
    type: string
    title: FPP Target
    displayText: FPP Target Name and public IP
    visible: true

#primaryOutputButton: ${rac_node_hostnames}
